import img from "../../../../assets/profile.png";

const partDummyTravelList = [
  {
    id: 1,
    profileImg: img,
    username: "가나다라",
    participants: 1,
    time: "점심•7/2(금)",
    location: "Nai Soie Beef Noodle",
    title: "카오산 근처에서 갈비 국수 드실 분!",
    tags: ["밥친구", "아무때나"],
  },
  {
    id: 2,
    profileImg: img,
    username: "홍길동",
    participants: 2,
    time: "점심•7/2(금)",
    location: "Nai Soie Beef Noodle",
    title: "홍대에서 맛집 탐방 같이 하실 분!",
    tags: ["혼밥러", "주말"],
  },
  {
    id: 3,
    profileImg: img,
    username: "홍길동",
    participants: 2,
    time: "점심•7/2(금)",
    location: "Nai Soie Beef Noodle",
    title: "홍대에서 맛집 탐방 같이 하실 분!",
    tags: ["혼밥러", "주말"],
  },
  {
    id: 4,
    profileImg: img,
    username: "홍길동",
    participants: 2,
    time: "점심•7/2(금)",
    location: "Nai Soie Beef Noodle",
    title: "홍대에서 맛집 탐방 같이 하실 분!",
    tags: ["혼밥러", "주말"],
  },
  {
    id: 5,
    profileImg: img,
    username: "홍길동",
    participants: 2,
    time: "점심•7/2(금)",
    location: "Nai Soie Beef Noodle",
    title: "홍대에서 맛집 탐방 같이 하실 분!",
    tags: ["혼밥러", "주말"],
  },
  {
    id: 6,
    profileImg: img,
    username: "홍길동",
    participants: 2,
    time: "점심•7/2(금)",
    location: "Nai Soie Beef Noodle",
    title: "홍대에서 맛집 탐방 같이 하실 분!",
    tags: ["혼밥러", "주말"],
  },
];

export default partDummyTravelList;
